export const employeeInfo = [
  {
    EmployeeID: 7817,
    EmployeeTitle: "Field Labor",
    FirstName: "Rusty",
    LastName: "Padilla",
  },
  {
    EmployeeID: 7812,
    EmployeeTitle: "Field Labor",
    FirstName: "Christopher",
    LastName: "Gerena",
  },
  {
    EmployeeID: 7815,
    EmployeeTitle: "Field Labor",
    FirstName: "Cameron",
    LastName: "Baker",
  },
  {
    EmployeeID: 7811,
    EmployeeTitle: "Field Labor",
    FirstName: "Mark",
    LastName: "Parker",
  },
  {
    EmployeeID: 7810,
    EmployeeTitle: "Field Labor",
    FirstName: "Keith",
    LastName: "Spencer",
  },
  {
    EmployeeID: 7809,
    EmployeeTitle: "Field Labor",
    FirstName: "Gabino",
    LastName: "Martinez",
  },
  {
    EmployeeID: 7798,
    EmployeeTitle: "",
    FirstName: "Alfonso",
    LastName: "Gaytan",
  },
  {
    EmployeeID: 7808,
    EmployeeTitle: "Field Labor",
    FirstName: "Herman",
    LastName: "Quevedo",
  },
  {
    EmployeeID: 7807,
    EmployeeTitle: "Field Labor",
    FirstName: "Jose",
    LastName: "Garcia",
  },
  {
    EmployeeID: 7805,
    EmployeeTitle: "Field Labor",
    FirstName: "Omar",
    LastName: "Rodriguez",
  },
  {
    EmployeeID: 7806,
    EmployeeTitle: "Field Labor",
    FirstName: "Mario",
    LastName: "Arellano",
  },
  {
    EmployeeID: 7802,
    EmployeeTitle: "Field Labor",
    FirstName: "Francisco",
    LastName: "Carrillo",
  },
  {
    EmployeeID: 7804,
    EmployeeTitle: "Field Labor",
    FirstName: "Joshua",
    LastName: "Park",
  },
  {
    EmployeeID: 7800,
    EmployeeTitle: "Field Labor",
    FirstName: "Ralph",
    LastName: "Vizcaino",
  },
  {
    EmployeeID: 7801,
    EmployeeTitle: "Field Labor",
    FirstName: "Miguel",
    LastName: "San Agustin",
  },
  {
    EmployeeID: 7797,
    EmployeeTitle: "Field Labor",
    FirstName: "Oscar",
    LastName: "Sanchez",
  },
  {
    EmployeeID: 7795,
    EmployeeTitle: "Project Engineer",
    FirstName: "Vrundan",
    LastName: "Sangani",
  },
  {
    EmployeeID: 7790,
    EmployeeTitle: "Field Labor",
    FirstName: "Joel",
    LastName: "Berber",
  },
  {
    EmployeeID: 7789,
    EmployeeTitle: "Field Labor",
    FirstName: "Alfredo",
    LastName: "Ramirez",
  },
  {
    EmployeeID: 7757,
    EmployeeTitle: "Field Labor",
    FirstName: "Juan",
    LastName: "Ruiz",
  },
  {
    EmployeeID: 7793,
    EmployeeTitle: "Field Labor",
    FirstName: "Marcelino",
    LastName: "Ruiz",
  },
  {
    EmployeeID: 7794,
    EmployeeTitle: "Field Labor",
    FirstName: "Reyes",
    LastName: "Amigon",
  },
  {
    EmployeeID: 7792,
    EmployeeTitle: "Field Labor",
    FirstName: "Jose",
    LastName: "Ruiz",
  },
  {
    EmployeeID: 7791,
    EmployeeTitle: "Field Labor",
    FirstName: "Abraham",
    LastName: "Lopez",
  },
  {
    EmployeeID: 7787,
    EmployeeTitle: "Field Labor",
    FirstName: "Hugo",
    LastName: "Maldonado",
  },
  {
    EmployeeID: 7788,
    EmployeeTitle: "Field Labor",
    FirstName: "Jesus",
    LastName: "Torres",
  },
  {
    EmployeeID: 7784,
    EmployeeTitle: "Software Developer",
    FirstName: "Hyun Myung",
    LastName: "Kim",
  },
  {
    EmployeeID: 7779,
    EmployeeTitle: "Field Labor",
    FirstName: "Emmanuel",
    LastName: "Cerda",
  },
  {
    EmployeeID: 7781,
    EmployeeTitle: "Field Labor",
    FirstName: "Felipe",
    LastName: "Pastrana",
  },
  {
    EmployeeID: 7782,
    EmployeeTitle: "Field Labor",
    FirstName: "Pedro",
    LastName: "Carmona",
  },
  {
    EmployeeID: 7778,
    EmployeeTitle: "Field Labor",
    FirstName: "Dario",
    LastName: "Valdez",
  },
  {
    EmployeeID: 7775,
    EmployeeTitle: "Field Labor",
    FirstName: "Mark",
    LastName: "Hebron",
  },
  {
    EmployeeID: 7773,
    EmployeeTitle: "Field Labor",
    FirstName: "Daniel",
    LastName: "Reyes",
  },
  {
    EmployeeID: 7774,
    EmployeeTitle: "Field Labor",
    FirstName: "Pablo",
    LastName: "Jimenez",
  },
  {
    EmployeeID: 7771,
    EmployeeTitle: "Field Labor",
    FirstName: "Joseph",
    LastName: "Delgado",
  },
  {
    EmployeeID: 7772,
    EmployeeTitle: "Field Labor",
    FirstName: "Eric",
    LastName: "Garcia",
  },
  {
    EmployeeID: 7776,
    EmployeeTitle: "Field Labor",
    FirstName: "Angel",
    LastName: "Munoz",
  },
  {
    EmployeeID: 7777,
    EmployeeTitle: "Field Labor",
    FirstName: "Alfonso",
    LastName: "Papa",
  },
  {
    EmployeeID: 7770,
    EmployeeTitle: "Field Labor",
    FirstName: "Hector",
    LastName: "Rivera",
  },
  {
    EmployeeID: 7769,
    EmployeeTitle: "Field Labor",
    FirstName: "Raul",
    LastName: "Duenas",
  },
  {
    EmployeeID: 7768,
    EmployeeTitle: "Field Labor",
    FirstName: "Jose",
    LastName: "Ruano",
  },
  {
    EmployeeID: 7766,
    EmployeeTitle: "Field Labor",
    FirstName: "Jorge",
    LastName: "Moreno",
  },
  {
    EmployeeID: 7594,
    EmployeeTitle: "Field Labor",
    FirstName: "Oscar",
    LastName: "Rogel",
  },
  {
    EmployeeID: 7738,
    EmployeeTitle: "Field Labor",
    FirstName: "Efrain",
    LastName: "Lopez",
  },
  {
    EmployeeID: 7742,
    EmployeeTitle: "Field Labor",
    FirstName: "Quinton",
    LastName: "Crenshaw",
  },
  {
    EmployeeID: 7763,
    EmployeeTitle: "Field Labor",
    FirstName: "Damiyan",
    LastName: "Williams",
  },
  {
    EmployeeID: 7765,
    EmployeeTitle: "Field Labor",
    FirstName: "Aaron",
    LastName: "Roe",
  },
  {
    EmployeeID: 7761,
    EmployeeTitle: "Field Labor",
    FirstName: "Bryant",
    LastName: "Reyes",
  },
  {
    EmployeeID: 7762,
    EmployeeTitle: "Field Labor",
    FirstName: "Gilberto",
    LastName: "Moreno",
  },
  {
    EmployeeID: 7756,
    EmployeeTitle: "Field Labor",
    FirstName: "Javier",
    LastName: "Luna",
  },
  {
    EmployeeID: 7759,
    EmployeeTitle: "Field Labor",
    FirstName: "Mario",
    LastName: "Garcia",
  },
  {
    EmployeeID: 7760,
    EmployeeTitle: "Field Labor",
    FirstName: "Marcos",
    LastName: "Rodriguez",
  },
  {
    EmployeeID: 7767,
    EmployeeTitle: "Field Labor",
    FirstName: "Raul",
    LastName: "Mendoza",
  },
  {
    EmployeeID: 7755,
    EmployeeTitle: "Field Labor",
    FirstName: "Ignacio",
    LastName: "Bautista",
  },
  {
    EmployeeID: 7753,
    EmployeeTitle: "Project Manager",
    FirstName: "Martin",
    LastName: "Taylor",
  },
  {
    EmployeeID: 7752,
    EmployeeTitle: "Field Labor",
    FirstName: "Luis",
    LastName: "Perez",
  },
  {
    EmployeeID: 7750,
    EmployeeTitle: "Field Labor",
    FirstName: "Felipe",
    LastName: "Ostorga",
  },
  {
    EmployeeID: 7751,
    EmployeeTitle: "Field Labor",
    FirstName: "Francisco",
    LastName: "Zavala",
  },
  {
    EmployeeID: 7748,
    EmployeeTitle: "Field Labor",
    FirstName: "Luis",
    LastName: "Roman",
  },
  {
    EmployeeID: 7749,
    EmployeeTitle: "Field Labor",
    FirstName: "Andres",
    LastName: "Santana",
  },
  {
    EmployeeID: 7737,
    EmployeeTitle: "Field Labor",
    FirstName: "Bryan",
    LastName: "Guzman",
  },
  {
    EmployeeID: 7733,
    EmployeeTitle: "Field Labor",
    FirstName: "Mario",
    LastName: "Polendo",
  },
  {
    EmployeeID: 7734,
    EmployeeTitle: "Field Labor",
    FirstName: "Rudy",
    LastName: "Vargas",
  },
  {
    EmployeeID: 7732,
    EmployeeTitle: "Field Labor",
    FirstName: "Angel",
    LastName: "Padilla",
  },
  {
    EmployeeID: 7729,
    EmployeeTitle: "Field Labor",
    FirstName: "Vincent",
    LastName: "Manfre",
  },
  {
    EmployeeID: 7728,
    EmployeeTitle: "Field Labor",
    FirstName: "Alfredo",
    LastName: "Cervantes",
  },
  {
    EmployeeID: 7726,
    EmployeeTitle: "Field Labor",
    FirstName: "Joseph",
    LastName: "Ramos",
  },
  {
    EmployeeID: 7723,
    EmployeeTitle: "Field Labor",
    FirstName: "Stephen",
    LastName: "Haro",
  },
  {
    EmployeeID: 7724,
    EmployeeTitle: "Field Labor",
    FirstName: "Bruno",
    LastName: "Lopez",
  },
  {
    EmployeeID: 7717,
    EmployeeTitle: "Human Resource",
    FirstName: "Robert",
    LastName: "Kim",
  },
  {
    EmployeeID: 7718,
    EmployeeTitle: "Field Labor",
    FirstName: "Rafael",
    LastName: "Guevara",
  },
  {
    EmployeeID: 7708,
    EmployeeTitle: "Field Labor",
    FirstName: "Humberto",
    LastName: "Gutierrez",
  },
  {
    EmployeeID: 7707,
    EmployeeTitle: "Field Labor",
    FirstName: "Matthew",
    LastName: "Mendoza",
  },
  {
    EmployeeID: 7706,
    EmployeeTitle: "Field Labor",
    FirstName: "Angel",
    LastName: "Torres",
  },
  {
    EmployeeID: 7700,
    EmployeeTitle: "Field Labor",
    FirstName: "Angel",
    LastName: "Pasaye",
  },
  {
    EmployeeID: 7699,
    EmployeeTitle: "Field Labor",
    FirstName: "Aaron",
    LastName: "Joseph",
  },
  {
    EmployeeID: 7679,
    EmployeeTitle: "Project Engineer",
    FirstName: "Zi Ying",
    LastName: "Liang",
  },
  {
    EmployeeID: 7680,
    EmployeeTitle: "Project Manager",
    FirstName: "Saeid",
    LastName: "Tavazoei",
  },
  {
    EmployeeID: 7677,
    EmployeeTitle: "Marketing",
    FirstName: "Daniel",
    LastName: "Ju",
  },
  {
    EmployeeID: 7675,
    EmployeeTitle: "Junior Estimator",
    FirstName: "Suji",
    LastName: "Ham",
  },
  {
    EmployeeID: 7667,
    EmployeeTitle: "Field Labor",
    FirstName: "Salvador",
    LastName: "Ochoa",
  },
  {
    EmployeeID: 7576,
    EmployeeTitle: "Estimator",
    FirstName: "Russel",
    LastName: "Viloria",
  },
  {
    EmployeeID: 7603,
    EmployeeTitle: "Project Engineer",
    FirstName: "Yingcheng",
    LastName: "Zhu",
  },
  {
    EmployeeID: 7596,
    EmployeeTitle: "Project Engineer",
    FirstName: "Chaitanya",
    LastName: "Thalati",
  },
  {
    EmployeeID: 7536,
    EmployeeTitle: "Accountant",
    FirstName: "Hyun Ho",
    LastName: "Lee",
  },
  {
    EmployeeID: 7524,
    EmployeeTitle: "Project Engineer",
    FirstName: "Isaac",
    LastName: "Shin",
  },
  {
    EmployeeID: 7484,
    EmployeeTitle: "Project Engineer",
    FirstName: "Donghyuk",
    LastName: "Kim",
  },
  {
    EmployeeID: 7507,
    EmployeeTitle: "Field Labor",
    FirstName: "Anthony",
    LastName: "Gauthier",
  },
  {
    EmployeeID: 7492,
    EmployeeTitle: "Estimator",
    FirstName: "Paul",
    LastName: "Oh",
  },
  {
    EmployeeID: 7472,
    EmployeeTitle: "Field Labor",
    FirstName: "Javier",
    LastName: "Morales",
  },
  {
    EmployeeID: 7474,
    EmployeeTitle: "Field Labor",
    FirstName: "Sergio",
    LastName: "Cerna",
  },
  {
    EmployeeID: 7446,
    EmployeeTitle: "Field Labor",
    FirstName: "Jesus Vinicio",
    LastName: "Torres Acuna",
  },
  {
    EmployeeID: 7447,
    EmployeeTitle: "Accountant",
    FirstName: "Seung Yunn",
    LastName: "Baek",
  },
  {
    EmployeeID: 7421,
    EmployeeTitle: "Roofer",
    FirstName: "Martin",
    LastName: "Rodriguez",
  },
  {
    EmployeeID: 7433,
    EmployeeTitle: "Project Engineer",
    FirstName: "Parth",
    LastName: "Patel",
  },
  {
    EmployeeID: 7423,
    EmployeeTitle: "Software Developer",
    FirstName: "Sangbin",
    LastName: "Whi",
  },
  {
    EmployeeID: 7420,
    EmployeeTitle: "Project Engineer",
    FirstName: "Dongseon",
    LastName: "Kim",
  },
  {
    EmployeeID: 7407,
    EmployeeTitle: "Accountant",
    FirstName: "Hyunho",
    LastName: "Goo",
  },
  {
    EmployeeID: 7399,
    EmployeeTitle: "Field Labor",
    FirstName: "Alexander",
    LastName: "Ayala",
  },
  {
    EmployeeID: 7402,
    EmployeeTitle: "Roofer",
    FirstName: "Frank",
    LastName: "Chavez",
  },
  {
    EmployeeID: 7401,
    EmployeeTitle: "Field Labor",
    FirstName: "Sun",
    LastName: "Kim",
  },
  {
    EmployeeID: 7398,
    EmployeeTitle: "Field Labor",
    FirstName: "Michael",
    LastName: "Lave",
  },
  {
    EmployeeID: 7387,
    EmployeeTitle: "Estimator",
    FirstName: "Vi",
    LastName: "Dinh",
  },
  {
    EmployeeID: 7372,
    EmployeeTitle: "Roofer",
    FirstName: "Marcos",
    LastName: "Garcia Rios",
  },
  {
    EmployeeID: 7348,
    EmployeeTitle: "Field Labor",
    FirstName: "Abel Jr",
    LastName: "Vergara",
  },
  {
    EmployeeID: 7356,
    EmployeeTitle: "Field Labor",
    FirstName: "Jeffrey",
    LastName: "Mortimer",
  },
  {
    EmployeeID: 7350,
    EmployeeTitle: "Field Labor",
    FirstName: "Onecimo",
    LastName: "Perez",
  },
  {
    EmployeeID: 7300,
    EmployeeTitle: "Project Manager",
    FirstName: "Yatindra",
    LastName: "Shah",
  },
  {
    EmployeeID: 7310,
    EmployeeTitle: "Roofer",
    FirstName: "Steven",
    LastName: "Rangel",
  },
  {
    EmployeeID: 7313,
    EmployeeTitle: "Field Labor",
    FirstName: "George",
    LastName: "Sanchez",
  },
  {
    EmployeeID: 7312,
    EmployeeTitle: "Field Labor",
    FirstName: "Antwoine",
    LastName: "Degrate",
  },
  {
    EmployeeID: 7304,
    EmployeeTitle: "Project Manager",
    FirstName: "Zhuoran",
    LastName: "Wang",
  },
  {
    EmployeeID: 7275,
    EmployeeTitle: "Roofer",
    FirstName: "Rodolfo",
    LastName: "Nava",
  },
  {
    EmployeeID: 7272,
    EmployeeTitle: "Accountant",
    FirstName: "Soo Jung",
    LastName: "Chae",
  },
  {
    EmployeeID: 7243,
    EmployeeTitle: "Field Labor",
    FirstName: "Gerald",
    LastName: "Clingan",
  },
  {
    EmployeeID: 7238,
    EmployeeTitle: "Field Labor",
    FirstName: "Miguel",
    LastName: "Ibarra",
  },
  {
    EmployeeID: 7229,
    EmployeeTitle: "Field Labor",
    FirstName: "Edward",
    LastName: "Shay",
  },
  {
    EmployeeID: 7219,
    EmployeeTitle: "Human Resource",
    FirstName: "Christopher",
    LastName: "Kim",
  },
  {
    EmployeeID: 7216,
    EmployeeTitle: "Field Labor",
    FirstName: "Victor",
    LastName: "Lopez",
  },
  {
    EmployeeID: 7215,
    EmployeeTitle: "Field Labor",
    FirstName: "Marshall",
    LastName: "Silva",
  },
  {
    EmployeeID: 7207,
    EmployeeTitle: "Field Labor",
    FirstName: "Jesse",
    LastName: "Beebe",
  },
  {
    EmployeeID: 7203,
    EmployeeTitle: "Field Labor",
    FirstName: "Virgilio",
    LastName: "Martinez",
  },
  {
    EmployeeID: 7184,
    EmployeeTitle: "Dispatcher",
    FirstName: "Justin",
    LastName: "Kim",
  },
  {
    EmployeeID: 7185,
    EmployeeTitle: "Project Manager",
    FirstName: "Seunghyun",
    LastName: "Yang",
  },
  {
    EmployeeID: 7171,
    EmployeeTitle: "Field Labor",
    FirstName: "Raul Jr",
    LastName: "Rangel",
  },
  {
    EmployeeID: 7169,
    EmployeeTitle: "Field Labor",
    FirstName: "Cesar",
    LastName: "Delgadillo",
  },
  {
    EmployeeID: 7162,
    EmployeeTitle: "Field Labor",
    FirstName: "Marvin",
    LastName: "Alvarado",
  },
  {
    EmployeeID: 7158,
    EmployeeTitle: "Field Labor",
    FirstName: "Guillermo",
    LastName: "Lagunas",
  },
  {
    EmployeeID: 7156,
    EmployeeTitle: "Field Labor",
    FirstName: "Isidro",
    LastName: "Briseno",
  },
  {
    EmployeeID: 7153,
    EmployeeTitle: "Field Labor",
    FirstName: "Adrian",
    LastName: "Gonzalez",
  },
  {
    EmployeeID: 7152,
    EmployeeTitle: "Project Manager",
    FirstName: "Taeho",
    LastName: "Kim",
  },
  {
    EmployeeID: 7141,
    EmployeeTitle: "Estimator",
    FirstName: "Sergio",
    LastName: "Franco",
  },
  {
    EmployeeID: 7135,
    EmployeeTitle: "Project Manager",
    FirstName: "Peter",
    LastName: "Jun",
  },
  {
    EmployeeID: 7123,
    EmployeeTitle: "Project Manager",
    FirstName: "Andrew",
    LastName: "Kwon",
  },
  {
    EmployeeID: 7121,
    EmployeeTitle: "Project Manager",
    FirstName: "Alex",
    LastName: "Lee",
  },
  {
    EmployeeID: 7088,
    EmployeeTitle: "Project Manager",
    FirstName: "Richard",
    LastName: "Delaloza",
  },
  {
    EmployeeID: 7012,
    EmployeeTitle: "Field Labor",
    FirstName: "Josue",
    LastName: "Gaitan",
  },
  {
    EmployeeID: 7021,
    EmployeeTitle: "Field Labor",
    FirstName: "Mariano",
    LastName: "Mandujano",
  },
  {
    EmployeeID: 7049,
    EmployeeTitle: "Field Labor",
    FirstName: "Jose",
    LastName: "Solis",
  },
  {
    EmployeeID: 7018,
    EmployeeTitle: "Field Labor",
    FirstName: "Don",
    LastName: "Cowan",
  },
  {
    EmployeeID: 7014,
    EmployeeTitle: "Field Labor",
    FirstName: "Rafael",
    LastName: "Chavez Jr",
  },
  {
    EmployeeID: 7015,
    EmployeeTitle: "Field Labor",
    FirstName: "Andres",
    LastName: "Chimalpopoca",
  },
  {
    EmployeeID: 5020,
    EmployeeTitle: "President",
    FirstName: "Jae",
    LastName: "Jung",
  },
  {
    EmployeeID: 5023,
    EmployeeTitle: "Estimator",
    FirstName: "Hee Bum",
    LastName: "Yang",
  },
  {
    EmployeeID: 5001,
    EmployeeTitle: "Vice President",
    FirstName: "Don",
    LastName: "Seo",
  },
  {
    EmployeeID: 7739,
    EmployeeTitle: "Field Labor",
    FirstName: "Mike",
    LastName: "Marquez",
  },
  {
    EmployeeID: 7685,
    EmployeeTitle: "Field Labor",
    FirstName: "Steven",
    LastName: "Cucci",
  },
  {
    EmployeeID: 7818,
    EmployeeTitle: "Field Labor",
    FirstName: "Raul",
    LastName: "Gonzalez",
  },
  {
    EmployeeID: 7714,
    EmployeeTitle: "Field Labor",
    FirstName: "Gilberto",
    LastName: "Flores",
  },
  {
    EmployeeID: 7745,
    EmployeeTitle: "Field Labor",
    FirstName: "Valdemar",
    LastName: "Garcia",
  },
  {
    EmployeeID: 7746,
    EmployeeTitle: "Field Labor",
    FirstName: "Conrad",
    LastName: "Montano",
  },
  {
    EmployeeID: 7747,
    EmployeeTitle: "Field Labor",
    FirstName: "Manuel",
    LastName: "Estrada",
  },
  {
    EmployeeID: 7740,
    EmployeeTitle: "Field Labor",
    FirstName: "Osualdo",
    LastName: "Barajas",
  },
  {
    EmployeeID: 7743,
    EmployeeTitle: "Field Labor",
    FirstName: "Erika",
    LastName: "Gonzalez",
  },
  {
    EmployeeID: 7744,
    EmployeeTitle: "Field Labor",
    FirstName: "Filogonio",
    LastName: "Nunez",
  },
  {
    EmployeeID: 7785,
    EmployeeTitle: "Field Labor",
    FirstName: "Rafael",
    LastName: "Berber",
  },
  {
    EmployeeID: 7786,
    EmployeeTitle: "Field Labor",
    FirstName: "Walter",
    LastName: "Berber",
  },
  {
    EmployeeID: 7796,
    EmployeeTitle: "Field Labor",
    FirstName: "Justin",
    LastName: "Benitez",
  },
  {
    EmployeeID: 7819,
    EmployeeTitle: "Field Labor",
    FirstName: "Alejo",
    LastName: "Campos",
  },
  {
    EmployeeID: 7816,
    EmployeeTitle: "Field Labor",
    FirstName: "Jonathan",
    LastName: "Falcon",
  },
];
